version: '3'
services:
    mysql-semarjawa:
        container_name: mysql-semarjawa
        image: mysql:5.7
        command: ["--lower_case_table_names=1", "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always        
        volumes:
            - ${MYSQL_CONFIG_ROOT}/etc/mysql/conf.d:/etc/mysql/conf.d
            - ${MYSQL5_DATABASE_SEMAR_PATH}:/var/lib/mysql
        ports:
            - "3370:3306"
        networks:
            semarjawa-network:
                ipv4_address: 172.16.0.10

networks:
  semarjawa-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24